name: golang-pipeline
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.24.1
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4

      - name: Build
        run: go build -v ./...

  test:
    needs: build
    runs-on: ubuntu-latest
    container: golang:1.24.1
    steps:
      - uses: actions/checkout@v4

      - name: Run Unit Tests
        working-directory: final-main
        run: GOOS=linux GOARCH=amd64 go test ./...

      - name: Vet
        working-directory: final-main
        run: go vet ./...

  deploy:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: test
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ttekcor/final-main

      - name: Build and push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
